ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.yeshuwahane.fairsplit.ApplicationKt.module ]
    }
}

app {
    environment = "dev"
    environment = ${?APP_ENV}
}

database {
    url = ""
    url = ${?DATABASE_URL}
    maxPoolSize = 10
}

jwt {
    secret = "fairsplit-development-secret-key-32-chars-minimum"
    secret = ${?JWT_SECRET}
    issuer = "fairsplit"
    audience = "fairsplit-api"
    accessTtlDays = 30
    accessTtlDays = ${?JWT_ACCESS_TTL_DAYS}
    refreshTtlDays = 90
    refreshTtlDays = ${?JWT_REFRESH_TTL_DAYS}
}

storage {
    uploadDir = "uploads"
    uploadDir = ${?UPLOAD_DIR}
}
